### ISSUE TITLE
Leading whitespaces

### ISSUE THREAD

**Issue by n-studio** [HendrikNoeller/Writer#4]
Before live preview I used to use whitespaces to format the text.

Advantages:
* It's ignored when converted into PDF
* It's formatted in other text editors like Textmate or SublimeText

Is there a way to make live preview compatible with leading whitespaces?
Maybe having 3 modes: raw, live preview (ignores leading whitespaces), print (ignores leading whitespaces too)

**Comment by HendrikNoeller** [comment]
Hello,
I just released V2.0.1 which has a toggle to deactivate Live Preview in the Window menu. I hope this will help you part of the way until I can get to implementing ignoring leading whitespace

**Comment by n-studio** [comment]
That's great!
Thank you!
