### ISSUE TITLE
Pages of screenplays without a title page are numbered wrong in export

### ISSUE THREAD

**Issue by DrOverbuild** [HendrikNoeller/Writer#7]
So just a minute ago I went to export a short screenplay I had written, but forgot a title page. I exported it to PDF, and when I looked at the result, I noticed that the page numbers still started on the second page.

I'm guessing that Writer assumes there is always a title page when exporting.

**Comment by HendrikNoeller** [comment]
I'm gonna check out the issue and keep you updated...

**Comment by HendrikNoeller** [comment]
Fixed in commit afe9ef86b268117a60e8ed154a15ee55d6fac3f7
