### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by zenashopson** [HendrikNoeller/Writer#9]
Are there going to be anymore updates to this application writer

**Comment by HendrikNoeller** [comment]
Yes, I'm gonna update the program periodically as I have new feature ideas, as the fountain language progresses and as I have time to spare to work on a free product. 
My main goal is to keep Writer a sleek and elegant solution for screenwriting, which makes it unlikely that I will add things like storyboards or character profiles - that would conflict with the fountain spirit of having a sleek, plaintext readable file.
I'm more interested in adding functionality that makes working with fountain easier. For example, I'm working on the ability to reorder scenes in the outline view to avoid cutting and pasting big parts of a screenplay, and I'm thinking about adding a tool to quickly rename a character everywhere in the screenplay from a list of characters that occur in the file
